In [ ]:
pip install prettytable

In [9]:
import requests
import json
import prettytable
import pprint
import  pandas as pd
import csv
import os

In [23]:
csvpath = os.path.join("state_codes.csv")
with open(csvpath) as csvfile:
    csvreader = csv.reader(csvfile, delimiter=",")
    i=1
    # Loop through looking for the video
    for row in csvreader:
        if row[0] != "STATE":
            print(row[0] + "-" + row[1])
            latest_data_url = "https://api.bls.gov/publicAPI/v2/timeseries/data/" + "LAUST"+ row[0] + '0000000000003' + "?registrationkey=aa0178058edc459288bae0b8f2e6c502"
            p = requests.get(latest_data_url)
            json_data = json.loads(p.text)
            pprint.pprint(json_data)
            jsonfile = "LAUST"+ row[0] + '0000000000003' + ".json"
            with open(jsonfile, 'w') as f:
                json.dump(json_data, f, ensure_ascii=False)
#        if i > 6:
#            break
#        if row[0] == '23':
#            break
        i = i+1

23-Maine
25-Massachusetts
26-Michigan
30-Montana
32-Nevada
34-New Jersey
36-New York
37-North Carolina
39-Ohio
42-Pennsylvania
44-Rhode Island
47-Tennessee
48-Texas
49-Utah
53-Washington
55-Wisconsin
72-Puerto Rico
24-Maryland
01-Alabama
02-Alaska
04-Arizona
05-Arkansas
06-California
{'Results': {'series': [{'data': [{'footnotes': [{'code': 'P',
                                                  'text': 'Preliminary.'}],
                                   'latest': 'true',
                                   'period': 'M11',
                                   'periodName': 'November',
                                   'value': '5.4',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M10',
                                   'periodName': 'October',
                                   'value': '6.1',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M09',
                                   'periodName': 'September',
                                   'value': '6.4',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M08',
                                   'periodName': 'August',
                                   'value': '7.5',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M07',
                                   'periodName': 'July',
                                   'value': '7.9',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M06',
                                   'periodName': 'June',
                                   'value': '8.0',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M05',
                                   'periodName': 'May',
                                   'value': '7.5',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M04',
                                   'periodName': 'April',
                                   'value': '8.1',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M03',
                                   'periodName': 'March',
                                   'value': '8.2',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M02',
                                   'periodName': 'February',
                                   'value': '8.4',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M01',
                                   'periodName': 'January',
                                   'value': '9.2',
                                   'year': '2021'},
                                  {'footnotes': [{}],
                                   'period': 'M12',
                                   'periodName': 'December',
                                   'value': '9.1',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M11',
                                   'periodName': 'November',
                                   'value': '8.3',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M10',
                                   'periodName': 'October',
                                   'value': '9.3',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M09',
                                   'periodName': 'September',
                                   'value': '10.5',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M08',
                                   'periodName': 'August',
                                   'value': '12.3',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M07',
                                   'periodName': 'July',
                                   'value': '13.6',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M06',
                                   'periodName': 'June',
                                   'value': '14.1',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M05',
                                   'periodName': 'May',
                                   'value': '15.5',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M04',
                                   'periodName': 'April',
                                   'value': '16.0',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M03',
                                   'periodName': 'March',
                                   'value': '5.1',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M02',
                                   'periodName': 'February',
                                   'value': '4.3',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M01',
                                   'periodName': 'January',
                                   'value': '4.5',
                                   'year': '2020'},
                                  {'footnotes': [{}],
                                   'period': 'M12',
                                   'periodName': 'December',
                                   'value': '3.9',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M11',
                                   'periodName': 'November',
                                   'value': '3.9',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M10',
                                   'periodName': 'October',
                                   'value': '3.9',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M09',
                                   'periodName': 'September',
                                   'value': '3.7',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M08',
                                   'periodName': 'August',
                                   'value': '4.3',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M07',
                                   'periodName': 'July',
                                   'value': '4.5',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M06',
                                   'periodName': 'June',
                                   'value': '4.2',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M05',
                                   'periodName': 'May',
                                   'value': '3.7',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M04',
                                   'periodName': 'April',
                                   'value': '3.9',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M03',
                                   'periodName': 'March',
                                   'value': '4.5',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M02',
                                   'periodName': 'February',
                                   'value': '4.4',
                                   'year': '2019'},
                                  {'footnotes': [{}],
                                   'period': 'M01',
                                   'periodName': 'January',
                                   'value': '4.9',
                                   'year': '2019'}],
                         'seriesID': 'LAUST060000000000003'}]},
 'message': [],
 'responseTime': 199,
 'status': 'REQUEST_SUCCEEDED'}

08-Colorado
09-Connecticut
10-Delaware
11-District of Columbia
12-Florida
13-Georgia
15-Hawaii
16-Idaho
17-Illinois
18-Indiana
19-Iowa
20-Kansas
21-Kentucky
22-Louisiana
27-Minnesota
28-Mississippi
29-Missouri
31-Nebraska
33-New Hampshire
35-New Mexico
38-North Dakota
40-Oklahoma
41-Oregon
45-South Carolina
46-South Dakota
50-Vermont
51-Virginia
54-West Virginia
56-Wyoming

In [4]:
df=pd.read_csv('state_codes.csv')
df.head()

   STATE           NAME
0     23          Maine
1     25  Massachusetts
2     26       Michigan
3     30        Montana
4     32         Nevada

In [7]:

for row in df.rows:
    headers = {'Content-type': 'application/json'}
    latest_data_url == "https://api.bls.gov/publicAPI/v2/timeseries/data/" + "LAUCN"+ row['STATE'] + '1210000000003' + "?registrationkey=aa0178058edc459288bae0b8f2e6c502"
    data = json.dumps({"seriesid": ['LAUCN131210000000003','LASST130000000000003'],"startyear":"2011", "endyear":"2021"})
    p = requests.get(latest_data_url)
    json_data = json.loads(p.text)
    pprint.pprint(json_data)

AttributeError: 'DataFrame' object has no attribute 'rows'

In [ ]:


headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LAUCN131210000000003','LASST130000000000003'],"startyear":"2011", "endyear":"2021"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
pprint.pprint(json_data)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.txt','w')
    output.write (x.get_string())
    output.close()